all: CBT.exe

CFLAGS=-c -W3 -AL -G2 -Ot -Oi -Ol -On -Og -Oc -Gs -DUSING_DOS

LIBS=oldnames+llibce+graphics
LFLAGS=/BATCH /NOD /FAR /PACKC /NOE
LINKER=link


OBJS  = CBT.obj ANALYZE.obj COMPUTE.obj CONFIG.obj DOSUTILS.obj \
	EXTERN.obj HANDNESS.obj 

CBT.exe: $(OBJS)
	@$(LINKER) @<<CBT.lrf
$(OBJS: =+^
)
CBT $(LFLAGS) /ST:15000
CBT
$(LIBS);
<<NOKEEP

